* Ordem de execução
** Etapa de pré-processamento
1. processa_medicoes.py
   2. gera_loadshapes.py
      3. extrai_dados_Loaddss_original.py
	 4. gera_arquivo_Load_dss.py 

* Descrição dos scripts

** processa_medicoes.py

Processa os dados originais disponibilizados por Bu et al., garantindo
a formatação das datas no padrão datetime,e as medições para tipo numérico.
Além disso, realiza verificações nos dataframes em busca de
inconsistências.

Os dados correspondem a uma rede de distribuição real composta por
3 alimentadores, aos quais estão conectados 1120 consumidores. Todos
os consumidores são equipados com smart meters que registram o consumo
horário de energia (kWh). O conjunto de dados disponibilizado contempla
1 ano de medições.

Para preservação da privacidade dos consumidores, as medições dos smart
meters são agregadas no nível secundário dos transformadores de distribuição,

formando nós (buses). Ao todo, o sistema é composto por 240 nós.
A potência reativa da rede foi determinada por meio da atribuição de
fatores de potência aleatórios aos nós (buses), no intervalo de 0,90 a
0,95. A metodologia de cálculo utilizada está descrita na planilha de dados disponibilizada pelos autores.


Referência:
F. Bu, Y. Yuan, Z. Wang, K. Dehghanpour, and A. Kimber, "A Time-series Distribution Test System based on Real
Utility Data." 2019 North American Power Symposium (NAPS), Wichita, KS, USA, 2019, pp. 1-6.
<https://wzy.ece.iastate.edu/Testsystem.html>

ENTRADA:
	+ arquivo "Calculated Nodal P&Q.xlsx" : arquivo original disponibilizado pelos autores.

SAÍDAS:
	+ arquivo "Nodal_PQ_processado.xlsx" : dados após processamento;
	+ arquivo "log_processamento_Nodal_PQ.txt" : relatório das verificações;
	+ figuras:
	  - FP_1DIA_FeederA.png : Plot do Fator de Potência ao longo de 1 dia no Feeder A.
	  - FP_1DIA_FeederB.png : Plot do Fator de Potência ao longo de 1 dia no Feeder B.
	  - FP_1DIA_FeederC.png : Plot do Fator de Potência ao longo de 1 dia no Feeder C.
	  - FP_1DIA_subestacao.png : Plot do Fator de Potência ao longo de 1 dia na subestação.
	  - FP_total_FeederA.png : Plot do Fator de Potência do Feeder A ao longo de todo o período disponível.
	  - FP_total_FeederB.png : Plot do Fator de Potência do Feeder B ao longo de todo o período disponível.
	  - FP_total_FeederC.png : Plot do Fator de Potência do Feeder C ao longo de todo o período disponível.
	  - FP_total _subestacao.png : Plot do Fator de Potência na subestação ao longo de todo o período disponível.
	  - potencia_1DIA_FeederA : Plot das potências ativa e reativa ao longo de 1 dia no Feeder A.
	  - potencia_1DIA_FeederB : Plot das potências ativa e reativa ao longo de 1 dia no Feeder B.
	  - potencia_1DIA_FeederC : Plot das potências ativa e reativa ao longo de 1 dia no Feeder C.
	  - potencia_1DIA_subestacao : Plot das potências ativa e reativa ao longo de 1 dia na subestação.
	  - potencia_total_FeederA.png : Plot das potências ativa e reativa do Feeder A ao longo de todo o período disponível.
	  - potencia_total_FeederB.png : Plot das potências ativa e reativa do Feeder B ao longo de todo o período disponível.
	  - potencia_total_FeederC.png : Plot das potências ativa e reativa do Feeder C ao longo de todo o período disponível.
	  - potencia_total_subestacao.png : Plot das potências ativa e reativa na subestação ao longo de todo o período disponível.


	
** gera_loadshapes.py

Realiza uma leitura da planilha 'Nodal_P&Q_processados.xlsx' e gera os arquivos .txt contendo os loadshapes de potência ativa em p.u (normalizados por unidade) por bus, e também os arquivos loadshapes.dss
que criam as cargas no OpenDss e apontam para os .txt

Etapas do processo:
	1. Leitura dos dados
	2. Eliminação das cargas nulas
	3. Para cada bus, estabelece o valor máximo da série como potência de base
	4. Realiza a normalização da série
	5. Salva a série normalizada (loadshapes) em arquivos .txt, sendo um para cada bus
	6. Gera o arquivo Loadshapes.dss para cada Feeder
	7. Salva os valores de base adotados em uma planilha para possibilitar a conferencia.


INPUTS:
	+ planilha 'Nodal_PQ_processados.xlsx'


OUTPUTS:
	+ arquivos .txt com o loadshape de cada bus. Padrão do nome do arquivo: FeederX_Bus_xxxx.txt | Ex.: FeederA_Bus_1003.txt
	  (arquivos são separados por Feeder)
	+ arquivo Loadshapes.dss para cada Feeder. Padrão do nome do arquivo: Loadshapes_FeederX | Ex.: Loadshapes_FeederA.dss
	+ arquivo .csv contendo os valores de base adotados. Padrão do nome do arquivo: Valores_de_Base_FeederX.csv | Ex.: Valores_de_Base_FeederA.csv
	+ relatório: log_gera_loadshapes.txt
	
** extrai_dados_Loaddss_original.py

O arquivo Load.dss original considera cargas estática e, portanto, é necessario a crição
de um novo arquivo Load.dss que considere os loadshapes das cargas.

Para isso, é preciso conhecer o as configurações (nome, numero de fases e tipo de conexão)
de cada carga.

Para tal, o script realiza a leitura linha a linha do arquivo "Load.dss" original e, por meiod
de buscas de padrões de texto (expressões regulares/regex) identifica as configurações de cada
carga e salva-as em uma arquivo .xlsx.

INPUTS:
	+ Arquivo Load.dss original: 'Load_Original.dss'

OUTPUT:
	+ Arquivo de configurações dos loads: 'configs_do_load.xlsx'


** gera_arquivo_Load_dss.py
Gera três arquivos Load.dss, sendo um para cada Feeder, com base nas configurações extraídas
para cada feeder, nos loadshapes e valores de base definidos durante a construção dos loadshapes.

INPUTS:
    - planilha .xlsx contendo as configurações do feeder;
    - planilha .csv contendo os valores de base adotados;
    - arquivos loadshapes.dss.

OUTPUTS:
    - Arquivos Load.dss por feeder;
    - Relatório com inconsistências em .xlsx.


* Guia Inputs e Outputs das funções

** processa_medicoes.py

| Função               | Inputs                      | Outputs                          |
|----------------------+-----------------------------+----------------------------------|
| processa_medicoes.py | "Calculated Nodal P&Q.xlsx" | "Nodal_PQ_processado.xlsx"       |
|                      |                             | "log_processamento_Nodal_PQ.txt" |
|                      |                             | Figuras(plots)                   |
	

** gera_loadshapes.py
| Função             | Inputs                     | Outputs                     |
|--------------------+----------------------------+-----------------------------|
| gera_loadshapes.py | 'Nodal_PQ_processado.xlsx' | FeederX_Bus_xxxx.txt        |
|                    |                            | Loadshapes_FeederX.dss      |
|                    |                            | Valores_de_Base_FeederX.csv |
|                    |                            | log_gera_loadshapes.txt     |

** extrai_dados_Loaddss_original.py
| Função                           | Inputs              | Outputs                |
|----------------------------------+---------------------+------------------------|
| extrai_dados_Loaddss_original.py | "Load_Original.dss" | "configs_do_load.xlsx" |

** gera_arquivo_Load_dss.py

| Função                   | Inputs                                | Outputs                         |
|--------------------------+---------------------------------------+---------------------------------|
| gera_arquivo_Load_dss.py | 'configs_do_load.xlsx'                | 'Loads_Feeder{nome feeder}.dss' |
|                          | 'Valores_de_Base_Feeder{nome feeder}' | 'log_gera_load_dss.xlsx'        |
|                          | 'Loadshapes_Feeder{nome feeder}'      |                                 |



* Estrutura de diretórios

#+BEGIN_SRC

BtM-PV-estimation/
│
├── dados/
│   ├── externos/
│   │   ├── Calculated Nodal P&Q.xlsx
│   │   ├── estacao_INMET_A853_cruz_alta.csv
│   │   ├── Load_Original.dss
│   │   ├── Master_Original.dss
│   │
│   │
│   ├── inputs/
│   │   ├── carga_base/  
            ├── FeederA/
                └── FeederX_Bus_xxxx.txt
  
            ├── FeederB/
                └── FeederX_Bus_xxxx.txt

            ├── FeederC/
                └── FeederX_Bus_xxxx.txt

            ├── Loads_FeederA.dss
            ├── Loads_FeederB.dss
            ├── Loads_FeederC.dss
            ├── Loadshapes_FeederA.dss
            ├── Loadshapes_FeederB.dss
            ├── Loadshapes_FeederC.dss
            ├── Valores_de_Base_FeederA.csv
            ├── Valores_de_Base_FeederB.csv
            ├── Valores_de_Base_FeederC.csv
                
│   ├── intermediarios/  
│   │   ├── Nodal_PQ_processado.xlsx
│   │   ├── configs_do_load.xlsx

├── documentacao/
  
  
├── figuras/
    ├── pre-processament
        ├── pre-processamento
            ├── FP_1DIA_FeederA.png
	    ├── FP_1DIA_FeederB.png
	    ├── FP_1DIA_FeederC.png
	    ├── FP_1DIA_subestacao.png
	    ├── FP_total_FeederA.png 
	    ├── FP_total_FeederB.png
	    ├── FP_total_FeederC.png
	    ├── FP_total _subestacao.png 
	    ├── potencia_1DIA_FeederA
	    ├── potencia_1DIA_FeederB
	    ├── potencia_1DIA_FeederC
	    ├── potencia_1DIA_subestacao
	    ├── potencia_total_FeederA.png 
	    ├── potencia_total_FeederB.png
	    ├── potencia_total_FeederC.png
	    ├── potencia_total_subestacao.png 



├── logs/
    ├── log_gera_load_dss.xlsx
    ├── log_processamento_Nodal_PQ.txt
    ├── log_gera_loadshapes.txt

  
├── __pycache__/

├── README.md  
  
├── scripts/  
  
#+END_SRC



├──

├──
│
└──

* Dependências

+ pandas
+ numpy
+ matplotlib
